server:
  port: 9001
spring:
  application:
    name: account-service
  cloud:
    config:
      #uri: http://localhost:9000
      discovery:
        enabled: true
        service-id: config-server

eureka:
    client:
      service-url:
        defaulZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        maxInterval: 5000